### ISSUE TITLE
Uncovered files and lines references are not working

### ISSUE THREAD

**Issue by jdrskr** [barecheck/code-coverage-action#207]
Hi!

As title says uncovered files and lines references are not working as expected. All anchors are undefined.

<img width="826" alt="Screenshot 2022-10-27 at 11 07 55" src="https://user-images.githubusercontent.com/29379913/198243507-22301a83-888d-48e9-9590-80f18102fcf5.png">

**Comment by vitaliimelnychuk** [comment]
Hey @jdrskr! 

Thanks for bringing it up. What barecheck code coverage action version are you using? Is it v1?

**Comment by jdrskr** [comment]
yes it is v1. here is configuration

```yaml            - name: Generate Code Coverage report
              id: code-coverage
              uses: barecheck/code-coverage-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  lcov-file: './coverage/lcov.info'
                  base-lcov-file: './lcov.info'
                  minimum-ratio: 0
                  send-summary-comment: true
                  show-annotations: 'warning'
`

**Comment by vitaliimelnychuk** [comment]
@jdrskr I just released a fix for it. Can you please check it on your side? Just running the action one more time should work now. 

Let me know if you have any other problems with this action. Any ideas for new features are really welcome :)

**Comment by jdrskr** [comment]
@vitaliimelnychuk it works now, thanks! :)
