### ISSUE TITLE
 Http error on await getChangedFiles

### ISSUE THREAD

**Issue by wesleymotaaraujo** [barecheck/code-coverage-action#212]
Hey guys,

I'm using your code-coverage-action in two workflows and I'm getting an HTTP Not Found error in one of them.

I've forked your repo to try to figure out the problem and I've noticed the error is happening where it tries to getChangedFiles.

Have you ever faced something similar? I was wondering if this was something related to Github credentials or something related to.

**Comment by vitaliimelnychuk** [comment]
Hello @wesleymotaaraujo , thanks for reaching out!

It's probably something related to the credentials you are passing to the action. There are two options `github-token` and `barecheck-github-app-token` that are described in https://github.com/barecheck/code-coverage-action#inputs. 
I would suggest installing the app and using the `barecheck-github-app-token` as auth method.

Can you please check if you have one of those properties passed in your workflow?

**Comment by vitaliimelnychuk** [comment]
Ahh, I see, another thing, there are no many benefits to having the action on `push` events. Usually, people use this action as part of `pull_request` template. 

Try to use this example as a starting point https://github.com/barecheck/code-coverage-action#workflow-example

**Comment by wesleymotaaraujo** [comment]
Thanks! @vitaliimelnychuk  I've reinstalled the application, changed the token and it worked. Thank you!

**Comment by wesleymotaaraujo** [comment]
Just closing the issue.
