### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by vladsha-dev** [barecheck/code-coverage-action#257]
Hello @vitaliimelnychuk 
It would be great if you updated your action to use Node.js 20, as Node.js 16 actions are deprecated on GitHub. This action is used for the CI on the project I am working on. It is a really useful tool!

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: barecheck/code-coverage-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by vitaliimelnychuk** [comment]
Hey @vladsha-dev , thanks for reaching out!

Sure, let me take a look over the weekend. If you'd like to contribute feel free to open a PR I would be more than happy to review / merge. 

It might be that the only one change we need to is to change the node.js version to build and the version here: https://github.com/barecheck/code-coverage-action/blob/v1/action.yml

**Comment by vladsha-dev** [comment]
Thanks @vitaliimelnychuk,
Sorry, I am not very familiar with developing GitHub actions.
Our team would appreciate the upgrade of your GitHub action to the new Node.js version.

**Comment by vitaliimelnychuk** [comment]
Hello @vladsha-dev, I just upgraded the deps and node version. There is no breaking change with the previous version so what you need to do on your side it's just update node version to 20 in your GitHub action. Please use Readme as an example of how to do it.

**Comment by vladsha-dev** [comment]
Hello @vitaliimelnychuk
Thank you very much!
