### ISSUE TITLE
Bad Credentials

### ISSUE THREAD

**Issue by vaishnav-canarys** [barecheck/code-coverage-action#270]
We are trying to set this up for GitHub Enterprise Server.

Is it mandatory that a GitHub App for barecheck needs to be installed. With github-token, keep getting "Bad Credentials".

**Comment by vitaliimelnychuk** [comment]
Hi, @vaishnav-canarys thanks for opening an issue. 

No, the app is not required and is only needed if you'd like to send metrics to simple cloud and see a view over all your projects. 

Here is an example how you can use it with GitHub Actions: https://github.com/barecheck/code-coverage-action/pull/271
