### ISSUE TITLE
failing to calculate percentage

### ISSUE THREAD

**Issue by boredland** [barecheck/code-coverage-action#50]
Hi there! Thank you for this fine action so far

I have a merged lcov file (merged using `npx lcov-result-merger 'packages/*/coverage/lcov.info' > lcov.info`):

https://gist.github.com/boredland/3df2fa7a815dbaa18e2f9ce5f442905e

While this action correctly displays the uncovered files, it fails to calculate the percentages above:

![image](https://user-images.githubusercontent.com/4662748/116259893-84beac00-a776-11eb-978e-d9b7e1206a0c.png)

The log output resembles the same:

```
lcov-file: lcov.info
base-lcov-file: lcov-base.info
Compare branch code coverage: NaN%
Base branch code coverage: NaN%
Code coverage diff: NaN%
send-summary-comment is enabled for this workflow
minimum-ratio: NaN
minimum-ratio is disabled for this workflow
Show annotations feature enabled
Warning: 14 lines are not covered with tests
Warning: 24-27 lines are not covered with tests
Warning: 15-18, 33-36 lines are not covered with tests
Warning: 14-17, 35-38 lines are not covered with tests
Warning: 26-29, 49-52 lines are not covered with tests
Warning: 14-17, 35-38 lines are not covered with tests
```

**Comment by boredland** [comment]
I realized this most likely is an issue with lcov-result-merger and will only reopen if I can verify it isn't

**Comment by melnychukvitaliy** [comment]
Hello @boredland !
Sorry, for late reply,  haven't got any notification :(

Thank you for reaching out, did you have a chance to review `lcov` file?  If possible, you can send me `lcov` file, I am happy to help.
