### ISSUE TITLE
Add "Title" option to support multiple coverage checks for monorepos

### ISSUE THREAD

**Issue by iKadmium** [barecheck/code-coverage-action#85]
We run a monorepo, and on a PR, each app in the repo gets a matrix build, with testing, etc. It'd be great to get a separate coverage report for each app in the repo. I think this could be done with a title option.

Currently when there are multiple runs, the existing comment gets overwritten.

**Comment by vitaliimelnychuk** [comment]
Hello @iKadmium !

Thanks you for reaching out.

Yes, it makes for me to have support of  monorepos and have different comments based on title. 

Does it work for you if we add `report-title` property for the action https://github.com/barecheck/code-coverage-action#inputs?

I also have plans to add Github checks support as a part of https://github.com/barecheck/code-coverage-action/issues/80 so this title could be used there also.

**Comment by vitaliimelnychuk** [comment]
The other idea that came to my mind is to have property `app-name` based on what we can build titles. 

@iKadmium What do you think about it?

**Comment by iKadmium** [comment]
Personally, I rather like the `app-name` property, for my purposes, at least. That makes it clear that monorepo support is the idea - `report-title` doesn't necessarily promise that, especially if some time in the future the action uses some other means to identify a comment.

**Comment by vitaliimelnychuk** [comment]
I agree, makes sense for me!

Will create a PR later today so we can test it, thank you again for the feedback.

**Comment by vitaliimelnychuk** [comment]
@iKadmium You can check PR I created recently https://github.com/barecheck/code-coverage-action/pull/88 and if you have any doubts just let me know.

You can use commit directly if you want to test it. I am going to check on my side also and if everything okay will release 0.5 version of the github action with support of monorepos

**Comment by vitaliimelnychuk** [comment]
Hey @iKadmium, @smgshanto I already released new version of action https://github.com/barecheck/code-coverage-action/releases/tag/v0.5.0.

Check it out and let me know if there is anything else I can help.

Thanks for reaching out!
